version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_mysql_user
      MYSQL_PASSWORD: your_mysql_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2000:2000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: your_mysql_user
      DB_PASSWORD: your_mysql_password
      DB_NAME: your_database_name

volumes:
  mysql_data:
